In [1]:
import numpy as np

### NUMPY INDEXING AND SLICING OF VECTORS

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
# indexing
arr[9]

np.int64(20)

In [6]:
# slicing
arr[1:5]

array([12, 13, 14, 15])

In [7]:
arr[:4]

array([11, 12, 13, 14])

In [8]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
arr[4:]

array([15, 16, 17, 18, 19, 20])

In [12]:
# to reverse string
reverse = arr[::-1]

### NUMPY INDEXING AND SLICING OF MATRIX

In [15]:
arr = np.arange(1, 31).reshape(6,5)
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [19]:
arr[0]

array([1, 2, 3, 4, 5])

In [20]:
arr[3]

array([16, 17, 18, 19, 20])

In [21]:
arr[0,0]

np.int64(1)

In [22]:
arr[0,4]

np.int64(5)

In [23]:
arr[5,4]

np.int64(30)

In [25]:
# slicing
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [28]:
slice1 = arr[3: , 3: ]
slice1

array([[19, 20],
       [24, 25],
       [29, 30]])

In [30]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

### BOOLEAN INDEXING

In [32]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [33]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [34]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])