In [1]:
import numpy as np

## ARRAY OPERATIONS

### Arithmetic operations

In [6]:
a1 = np.array([1, 2, 3, 4, 5])
a1
a2 = np.array([6, 7, 8, 9, 10])
a2

array([ 6,  7,  8,  9, 10])

In [10]:
# size of both the arrays must be same while performing arithmetic operations.
add = a1 + a2
add

array([ 7,  9, 11, 13, 15])

In [11]:
sub = a1 - a2
sub

array([-5, -5, -5, -5, -5])

In [12]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [13]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [14]:
a1 // a2

array([0, 0, 0, 0, 0])

In [15]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

### Broadcasting

In [16]:
l = [10, 20, 30, 40]
arr = np.array(l)

In [17]:
arr + 11

array([21, 31, 41, 51])

In [19]:
arr2 = np.arange(1, 26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [20]:
arr2 +11

array([[12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36]])

### Deep and Shallow copy

In [21]:
# shallow copy affect both
# deep copy does not affect origional
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [25]:
slice = a[:5]
slice

array([1, 2, 3, 4, 5])

In [26]:
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [27]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
a[4:6] * 10

array([50, 60])

In [29]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
b = a

In [31]:
b[0]=99


In [32]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [34]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
# deep copy does not affect origional source. 
c = a.copy()
c

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [36]:
c[0] = 11
c

array([11,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [37]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### Matrix operations

In [38]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [39]:
A 

array([[1, 2],
       [3, 4]])

In [41]:
B


array([[5, 6],
       [7, 8]])

In [42]:
# Dot product / matrix multiplication
A @ B

array([[19, 22],
       [43, 50]])

In [43]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [46]:
# Transpose
A

array([[1, 2],
       [3, 4]])

In [45]:
A.T

array([[1, 3],
       [2, 4]])

## Advance Array Manipulation

### Stacking Array

In [ ]:
# for stacking we use vectors, not matrix

In [53]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])


In [50]:
# vertical stack
np.vstack((a, b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [51]:
# horizontal stack
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
# coloum st
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### Splitting Array

In [55]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [56]:
# horizontal split
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [57]:
# vertical splito
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]