In [1]:
import numpy as np

Basic Array Creation

In [3]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [4]:
a = [1, 2, 3.5, "hello"]
a

[1, 2, 3.5, 'hello']

In [5]:
np.array(a)

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [6]:
b = [1, 2, 3.5]
b

[1, 2, 3.5]

In [7]:
np.array(b)

array([1. , 2. , 3.5])

In [8]:
# list
l = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
# 2D array
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation function

In [14]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [16]:
zero = np.zeros((4,8))
zero

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
one = np.ones((6,6))
one

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [22]:
# linear spacing
linspace = np.linspace(1,5,10)
linspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

Randoom Generation Function

In [24]:
# random varlues between 0 and 1
np.random.rand(10)

array([0.36737777, 0.47600393, 0.1162179 , 0.13562911, 0.44485775,
       0.83874242, 0.48833097, 0.98712025, 0.95661818, 0.71343786])

In [25]:
# standardization - random values between -3 to 3
np.random.randn(10)

array([-1.83665435, -0.60895212,  0.79565162,  2.986068  ,  0.64005063,
        1.23098425, -1.77083833,  0.93645998,  0.65415993,  0.36368424])

In [31]:
# gives any random number in range n - here range- 6
np.random.randint(6)

1

In [36]:
# 5 random numbers between 10 and 20 
np.random.randint(10,20,5)

array([15, 17, 16, 12, 13], dtype=int32)

Array Attributes

In [37]:
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr.shape

(3, 3)

In [39]:
arr.size

9

In [40]:
arr.dtype

dtype('int64')

Array Methods

In [41]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr.min()

np.int64(1)

In [44]:
arr.max()

np.int64(9)

In [45]:
arr.sum()

np.int64(45)

In [50]:
# column wise sum
np.sum(arr, axis=0)


array([12, 15, 18])

In [48]:
# row wise sum
np.sum(arr, axis= 1)

array([ 6, 15, 24])

In [51]:
arr.mean()

np.float64(5.0)

In [52]:
# standerd deviation
arr.std()

np.float64(2.581988897471611)

In [54]:
# index of max element
arr.argmax()

np.int64(8)

In [55]:
# index of min element
arr.argmin()

np.int64(0)

Reshaping and resizing

In [4]:
arr1 = np.arange(1,31)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [5]:
arr1.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])